app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: snaidu/nodejs:latest
    port: 8080
    config: []
    env:
       - key: key
         value: value
  service:
    type: NodePort
    port: 8080